name: dotenv
version: 1.0.0
description: Load environment variables from a `.env` file.
author: mockturtl <mockturtl@gmail.com>
homepage: https://github.com/mockturtl/dotenv
environment:
  sdk: '>=1.8.0 <3.0.0'
dependencies:
  args: ^1.0.0
  dart2_constant: ^1.0.0
  meta: ^1.0.2
dev_dependencies:
  test: any
  collection: any
