name: dotenv
version: 4.2.0

description: Load environment variables from a `.env` file.
homepage: https://github.com/mockturtl/dotenv
environment:
  sdk: '>=2.16.0 <4.0.0'

dependencies:
  args: ^2.3.0
  meta: ^1.7.0

dev_dependencies:
  tidy: ^3.1.0
  test: ^1.24.8
  collection: ^1.18.0
